run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt
    - goimports
    - revive
    - bodyclose
    - noctx
    - errorlint

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false
  errcheck:
    check-type-assertions: true
  errorlint:
    errorf: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
